version: '3'

volumes:
  node_modules:
services:
  docgen:
    build: .
    ports:
      - '3000:3000'
    command: npm run start:dev
    volumes:
      - ./:/app/
      # - node_modules:/app/node_modules/
